-- app_events: an ingest path that cannot be used as a write primitive.
--
-- The table has existed for a while with 0 rows and no code writing to it. It
-- also had this policy:
--
--     "Anyone can log an event"  INSERT  to anon, authenticated  (no check)
--
-- which is an unauthenticated, unlimited, unvalidated INSERT into a table
-- anybody can name their own columns on. That is the same shape as the
-- partner_events open-INSERT flagged in July, and it is the reason this
-- migration leads with a DROP rather than a CREATE.
--
-- WHAT REPLACES IT. One SECURITY DEFINER function, log_app_event(), which is
-- the only way anon or authenticated can get a row in. It enforces three
-- things the policy could not:
--
--   1. The event name is on a fixed allowlist. An unknown name is refused, so
--      the table cannot be filled with junk names and the dashboard's GROUP BY
--      stays meaningful.
--   2. Sixty events a minute per session. Past that it returns false and
--      writes nothing.
--   3. props is shaped: an object, at most 20 keys, values truncated to 200
--      characters. A metric is never worth an unbounded blob.
--
-- It also takes user_id from auth.uid() rather than from the caller, so a
-- client cannot attribute its events to somebody else.
--
-- WHY A FUNCTION AND NOT A POLICY. A WITH CHECK expression can validate a row
-- but cannot rate-limit one — it has no view of how many the session already
-- sent. The count has to happen somewhere that can read the table, which for
-- an anonymous caller means SECURITY DEFINER.
--
-- HONEST LIMIT. session_id is generated by the client, so a determined caller
-- can rotate it and get 60 more. This is a spend/noise control, not an
-- identity control; the allowlist is what stops the table being useful to an
-- attacker, and the rate limit is what stops it being expensive.

begin;

-- 0) The table itself, for the first time.
--
-- app_events exists in production but no migration ever created it — it was
-- made by hand in the dashboard, so until now the repo had no reproducible
-- definition of it and tests/db/run.sh had nothing to apply this against. This
-- block matches the live columns exactly and is a no-op there; on a fresh
-- cluster it is what makes the rest of this file testable.
create table if not exists public.app_events (
  id          bigserial primary key,
  event_name  text        not null,
  session_id  uuid,
  user_id     uuid,
  path        text,
  town        text,
  listing_id  uuid,
  partner_id  uuid,
  value_pence integer,
  props       jsonb       not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

-- 1) Close the open door.
drop policy if exists "Anyone can log an event" on public.app_events;

alter table public.app_events enable row level security;

-- No policies are added back. With RLS on and no permissive policy, anon and
-- authenticated cannot select, insert, update or delete directly at all; the
-- SECURITY DEFINER function below is the entire surface. Service role (the
-- admin endpoint) bypasses RLS as it always has.
revoke all on public.app_events from anon, authenticated;

-- 2) Indexes the two hot paths need.
-- The rate-limit count, which runs on every single insert.
create index if not exists app_events_session_recent_idx
  on public.app_events (session_id, created_at desc);
-- The dashboard, which is always "this event, over this window".
create index if not exists app_events_name_created_idx
  on public.app_events (event_name, created_at desc);

-- 3) The allowlist.
--
-- Deliberately a constant in the function rather than a table: adding an event
-- should be a reviewed one-line migration, not a row somebody can insert. The
-- names are exactly the day-one set from the build brief.
create or replace function public.log_app_event(
  p_event_name  text,
  p_session_id  uuid,
  p_props       jsonb   default '{}'::jsonb,
  p_path        text    default null,
  p_town        text    default null,
  p_listing_id  uuid    default null,
  p_partner_id  uuid    default null,
  p_value_pence integer default null
) returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  allowed constant text[] := array[
    'search', 'search_no_results', 'map_move',
    'gem_view', 'gem_locked_view',
    'listing_view', 'booking_start', 'booking_paid', 'booking_abandoned',
    'heading_tap', 'parked_tap', 'spot_taken_tap',
    'partner_impression', 'partner_click',
    'premium_paywall_view', 'premium_paid',
    'submit_spot_start', 'submit_spot_done',
    'qr_landing', 'share_tap',
    'hotspot_to_booking_tap'
  ];
  recent integer;
  clean  jsonb;
begin
  -- Unknown name: refuse. Returning false rather than raising keeps a bad
  -- client from seeing a stack trace, and keeps the caller's catch block quiet.
  if p_event_name is null or not (p_event_name = any(allowed)) then
    return false;
  end if;

  if p_session_id is null then
    return false;
  end if;

  select count(*) into recent
    from public.app_events
   where session_id = p_session_id
     and created_at > now() - interval '1 minute';

  if recent >= 60 then
    return false;
  end if;

  -- Shape props. Anything that is not an object becomes {}. Keys past the
  -- twentieth are dropped and string values are truncated; a metric payload
  -- has no business being longer than this.
  if p_props is null or jsonb_typeof(p_props) <> 'object' then
    clean := '{}'::jsonb;
  else
    select coalesce(jsonb_object_agg(k, v), '{}'::jsonb) into clean
      from (
        select key as k,
               case when jsonb_typeof(value) = 'string'
                    then to_jsonb(left(value #>> '{}', 200))
                    else value end as v
          from jsonb_each(p_props)
         order by key
         limit 20
      ) capped;
  end if;

  insert into public.app_events
    (event_name, session_id, user_id, path, town, listing_id, partner_id, value_pence, props)
  values
    (p_event_name, p_session_id, auth.uid(), left(p_path, 300), left(p_town, 120),
     p_listing_id, p_partner_id, p_value_pence, clean);

  return true;
end $$;

revoke all on function public.log_app_event(text, uuid, jsonb, text, text, uuid, uuid, integer) from public;
grant execute on function public.log_app_event(text, uuid, jsonb, text, text, uuid, uuid, integer)
  to anon, authenticated;

-- 4) The dashboard's one query.
--
-- Aggregation lives here rather than in the admin endpoint because PostgREST
-- makes GROUP BY awkward and the alternative is pulling every row over the
-- wire to count it in JavaScript — which stops working at exactly the volume
-- that makes the dashboard interesting.
--
-- service_role only. This function reads every event from every user, so anon
-- and authenticated are explicitly not granted it; the admin endpoint already
-- verifies the caller's email against the admin list before it calls in.
create or replace function public.app_events_summary(p_days integer default 30)
returns jsonb
language sql
security definer
set search_path = public, pg_temp
stable
as $$
  with window_events as (
    select * from public.app_events
     where created_at > now() - make_interval(days => greatest(1, least(p_days, 365))))
  select jsonb_build_object(
    'days', greatest(1, least(p_days, 365)),
    'generated_at', now(),

    -- Daily counts per event: the raw shape everything else is read against.
    'daily', coalesce((
      select jsonb_agg(r order by r->>'day' desc, r->>'event_name')
        from (select jsonb_build_object(
                'day', (created_at at time zone 'Europe/London')::date,
                'event_name', event_name,
                'n', count(*)) r
                from window_events
               group by (created_at at time zone 'Europe/London')::date, event_name) d), '[]'::jsonb),

    -- The two funnels the brief names. Counted in SESSIONS, not events: one
    -- person tapping three locked gems is one person who wanted them, and
    -- counting taps would flatter the conversion rate at every step.
    'premium_funnel', jsonb_build_object(
      'gem_locked_view',      (select count(distinct session_id) from window_events where event_name = 'gem_locked_view'),
      'premium_paywall_view', (select count(distinct session_id) from window_events where event_name = 'premium_paywall_view'),
      'premium_paid',         (select count(distinct session_id) from window_events where event_name = 'premium_paid')),

    'booking_funnel', jsonb_build_object(
      'listing_view',  (select count(distinct session_id) from window_events where event_name = 'listing_view'),
      'booking_start', (select count(distinct session_id) from window_events where event_name = 'booking_start'),
      'booking_paid',  (select count(distinct session_id) from window_events where event_name = 'booking_paid')),

    -- THE SUPPLY LIST. Every place somebody looked and found nothing to book,
    -- commonest first. This is the one output here meant to be acted on rather
    -- than watched.
    'no_results', coalesce((
      select jsonb_agg(r order by (r->>'n')::int desc)
        from (select jsonb_build_object(
                'query', coalesce(props->>'query', '(none)'),
                'town', coalesce(town, '(none)'),
                'n', count(*),
                'sessions', count(distinct session_id)) r
                from window_events
               where event_name = 'search_no_results'
               group by props->>'query', town
               order by count(*) desc
               limit 100) q), '[]'::jsonb)
  );
$$;

revoke all on function public.app_events_summary(integer) from public, anon, authenticated;
grant execute on function public.app_events_summary(integer) to service_role;

commit;
